config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :profiles
  resources :users, path: :usuarios, path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  resources :groups, path: 'grupos', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end
  
  resources :dealers, path: 'lojas', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  devise_for :users, path: :account, path_names: {
    sign_in: 'entrar',
    sign_out: 'sair',
    password: 'secret',
    confirmation: 'verificar',
    unlock: 'desbloquear',
    registration: 'minha-conta',
    sign_up: 'cadastre-se',
    edit: 'editar-perfil'
  }
  root to: 'pages#dashboard'

  get 'blank', to: "pages#blank"
  get 'chat', to: "pages#chat"
  get 'dashboard', to: "pages#chat"
  get 'home', to: "pages#index"
  
  #Routes for selects
  get 'dealers_by_group/:id', to: "select_options#dealers_by_group"

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  #Enums
  enum gender: { male: 0, female: 1, other: 2 }, _prefix: :kind

  def full_name
    [self.first_name, self.last_name].join(' ')
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AdminController
  before_action :set_user, only: %i[ edit update ]
  before_action :verify_password, only: [:update]

  # GET /profiles/1/edit
  def edit
    @user.build_profile if @user.profile.blank?
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @user.update(params_user)
        format.html { redirect_to @user, notice: "Perfil alterado com sucesso." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
 
  private
    def set_user
      @user = User.find(params[:id])
    end

    def params_user
      params_user = params.require(:user).permit(:email, :kind, :group_id, :dealer_id, :password, :password_confirmation, 
        profile_attributes: [:id, :first_name, :last_name, :gender, :birthdate])
    end

    def verify_password
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].extract!(:password, :password_confirmation)
      end
    end
end

app/views/profiles/_form.html.erb
<%= form_with(url: profile_path, model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :group_id, class:"form-label" %>
    <%= form.select :group_id, Group.order(name: :asc).collect { |c| [c.name, c.id] }, { prompt: 'Selecione o Grupo' }, { class: "form-control my-1 mr-2", id: "group_id_eq", onChange: "changeGroup()" } %>
  </div>
  
  <div class="mb-3">
    <%= form.label :dealer_id, class:"form-label" %>
    <%= form.select :dealer_id, @dealers ? @dealers : [], { prompt: 'Selecione uma Revenda' }, { class: "form-control my-1 mr-2", id: "dealer_id_eq" } %>
  </div>
  
      <%= form.fields_for :profile, user.profile do |profile_form| %>
          
          
          <div class="mb-3">
            <%= profile_form.label :first_name, class:"  form-label" %>
            <%= profile_form.text_field :first_name, class:"form-control", placeholder: "Nome"%>
          </div>

          <div class="mb-3">
            <%= profile_form.label :last_name, class:"form-label" %>
            <%= profile_form.text_field :last_name, class:"form-control", placeholder: "Sobrenome"%>
          </div>

          <div class="mb-3">
            <%= profile_form.label :gender, class:"col-md-3 col-form-label" %>
            <div class="col-md-9">
              <div class="form-group has-default bmd-form-group">
                <div class="form-check">
                  <label class="form-check-label">
                    <%= profile_form.radio_button :gender, 'male', class:"form-check-input" %> Masculino
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  </label>
                </div>

                <div class="form-check">
                  <label class="form-check-label">
                    <%= profile_form.radio_button :gender, 'female', class:"form-check-input" %> Feminino
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  </label>
                </div>

                <div class="form-check">
                  <label class="form-check-label">
                    <%= profile_form.radio_button :gender, 'other', class:"form-check-input" %> Outro
                    <span class="circle">
                      <span class="check"></span>
                    </span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          <div class="mb-3">
            <%= profile_form.label :birthdate, class:"col-md-3 col-form-label" %>
            <%= profile_form.date_field :birthdate, class:"form-control", placeholder: "Seu email"%>
          </div>
        <% end %>

  <div class="mb-3">
    <%= form.label :password, class:"form-label" %>
    <%= form.password_field :password, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation, class:"form-label" %>
    <%= form.password_field :password_confirmation, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :kind, class:"form-label" %>
    <%= form.select :kind, enum_options_for_select(model_class, :kind), {}, {class:"form-select"} %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
    <%= link_to 'Voltar', users_path, class:"btn btn-danger" %>
  </div>

          
<% end %>

<% content_for :javascripts do %>
  <script>
    $('#dealer_id_eq').prop('disabled', true);
    $("#group_id_eq").change(function() {
    $('#dealer_id_eq').prop('disabled', false);
    let id_group = $("#group_id_eq").val()
    $.get("/dealers_by_group/" + id_group, function (data) {
      let x
      $("#dealer_id_eq").html("")
      $("#dealer_id_eq").append('<option value ="">Selecione uma Revenda</option >')
      for (x in data) {
        let option = '<option value ="' + data[x].id + '">' + data[x].name + '</option >'
        $("#dealer_id_eq").append(option)
      }
    });
  })
  </script>
<% end %>

app/views/profiles/edit.html.erb
  <%- model_class = User -%>
  <div class="card">
    <div class="card-body">
      <h6 class="card-title">Editando Perfil</h6>
      <hr>
      <div class="col-12 col-lg-4">
        <%= render  partial: 'form', locals: { model_class: model_class, user: @user }  %>
      </div>
    </div>
  </div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthdate</th>
      <th>Gender</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.birthdate %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @profile.birthdate %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>