config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :profiles
  resources :users, path: :usuarios, path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  resources :groups, path: 'grupos', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end
  
  resources :dealers, path: 'lojas', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  devise_for :users, path: :account, path_names: {
    sign_in: 'entrar',
    sign_out: 'sair',
    password: 'secret',
    confirmation: 'verificar',
    unlock: 'desbloquear',
    registration: 'minha-conta',
    sign_up: 'cadastre-se',
    edit: 'editar-perfil'
  }
  root to: 'pages#dashboard'

  get 'blank', to: "pages#blank"
  get 'chat', to: "pages#chat"
  get 'dashboard', to: "pages#chat"
  get 'home', to: "pages#index"
  
  #Routes for selects
  get 'dealers_by_group/:id', to: "select_options#dealers_by_group"

end

app/views/layouts/shared/_footer.html.erb
<footer class="page-footer">
  <p class="mb-0">Copyright © <%= Date.today.year %> - <strong>RM Auto</strong>. Todos os direitos reservados.</p>
</footer>

app/views/layouts/shared/_navbar.html.erb
<!--sidebar wrapper -->
<div class="sidebar-wrapper overflow-auto" data-simplebar="true">
  <div class="sidebar-header">
    <div>
      <%= link_to root_path do %>
        <%= image_tag "theme/logo-icon.png", class:'logo-icon', alt:"logo icon" %>
      <% end %>
    </div>
    <div>
      <%= link_to root_path do %>
        <h4 class="logo-text">RM Auto</h4>
      <% end %>
    </div>
    <div class="toggle-icon ms-auto"><i class='bx bx-first-page'></i>
    </div>
  </div>
  <!--navigation-->
  <ul class="metismenu" id="menu">
    <li>
      <a href="javascript:;" class="has-arrow">
        <div class="parent-icon"><i class='bx bx-tachometer'></i>
        </div>
        <div class="menu-title">Dashboard</div>
      </a>
      <ul>
        <li> 
          <%= link_to root_path do %>
            <i class="bx bx-right-arrow-alt"></i>Home
          <% end %>
        </li>
        <li> 
          <%= link_to chat_path do %>
            <i class="bx bx-right-arrow-alt"></i>Chat
          <% end %>
        </li><li> 
          <%= link_to blank_path do %>
            <i class="bx bx-right-arrow-alt"></i>Blank Page
          <% end %>
        </li><li> 
          <%= link_to home_path do %>
            <i class="bx bx-right-arrow-alt"></i>Home?
          <% end %>
        </li>
      </ul>
    </li>

    <li class="menu-label">Configurações</li>
    <%
=begin%>
 <li>
      <a href="#">
        <div class="parent-icon"><i class='bx bx-briefcase-alt-2'></i>
        </div>
        <div class="menu-title">Gerenciar Grupos</div>
      </a>
    </li> 
<%
=end%>
    <li>
      <a href="javascript:;" class="has-arrow">
        <div class="parent-icon"><i class='bx bx-user' ></i>
        </div>
        <div class="menu-title">Gerenciar Usuários</div>
      </a>
      <ul>
        <li>
          <%= link_to users_path do %>
            <i class="bx bx-right-arrow-alt"></i>
            Listar Usuários
          <% end %>
        </li>
        <li>
        <%= link_to new_user_path do %>
          <i class="bx bx-plus"></i>Cadastrar Usuário
        <% end %>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:;" class="has-arrow">
        <div class="parent-icon"><i class='bx bx-buildings' ></i>
        </div>
        <div class="menu-title">Gerenciar Grupos</div>
      </a>
      <ul>
        <li>
          <%= link_to groups_path do %>
            <i class="bx bx-right-arrow-alt"></i>
            Listar Grupos
          <% end %>
        </li>
        <li>
        <%= link_to new_group_path do %>
          <i class="bx bx-plus"></i>Cadastrar Grupo
        <% end %>
        </li>
      </ul>
    </li>

    <li>
      <a href="javascript:;" class="has-arrow">
        <div class="parent-icon"><i class='bx bx-store-alt' ></i>
        </div>
        <div class="menu-title">Gerenciar Revendas</div>
      </a>
      <ul>
        <li>
          <%= link_to dealers_path do %>
            <i class="bx bx-right-arrow-alt"></i>
            Listar Revendas
          <% end %>
        </li>
        <li>
        <%= link_to new_dealer_path do %>
          <i class="bx bx-plus"></i>Cadastrar Revenda
        <% end %>
        </li>
      </ul>
    </li>

    <li>
      <a href="javascript:;" class="has-arrow">
        <div class="parent-icon"><i class='bx bx-group' ></i>
        </div>
        <div class="menu-title">Gerenciar Clientes</div>
      </a>
      <ul>
        <li>
          <%= link_to clients_path do %>
            <i class="bx bx-right-arrow-alt"></i>
            Listar Clientes
          <% end %>
        </li>
        <li>
        <%= link_to new_client_path do %>
          <i class="bx bx-plus"></i>Cadastrar Cliente
        <% end %>
        </li>
      </ul>
    </li>
    
  </ul>
  <!--end navigation-->
</div>
<!--end sidebar wrapper -->