config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :profiles
  resources :users, path: :usuarios, path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  resources :groups, path: 'grupos', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end
  
  resources :dealers, path: 'lojas', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  devise_for :users, path: :account, path_names: {
    sign_in: 'entrar',
    sign_out: 'sair',
    password: 'secret',
    confirmation: 'verificar',
    unlock: 'desbloquear',
    registration: 'minha-conta',
    sign_up: 'cadastre-se',
    edit: 'editar-perfil'
  }
  root to: 'pages#dashboard'

  get 'blank', to: "pages#blank"
  get 'chat', to: "pages#chat"
  get 'dashboard', to: "pages#chat"
  get 'home', to: "pages#index"
  
  #Routes for selects
  get 'dealers_by_group/:id', to: "select_options#dealers_by_group"

end

app/models/group.rb
class Group < ApplicationRecord
   has_many :dealers, class_name: "dealer", foreign_key: "group_id"
   ## ENUMS
   enum status: { waiting: 0, enabled: 1, disabled: 2 }, _prefix: :status
end

app/controllers/groups_controller.rb
class GroupsController < AdminController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Grupo criado com sucesso." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Grupo atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Grupo apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :status)
    end
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :status, class:"form-label" %>
    <%= form.select :status, enum_options_for_select(model_class, :status), {}, {class:"form-select"} %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
    <%= link_to 'Voltar', groups_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="card">
  <div class="card-body">
    <h6 class="card-title">Editando Grupo</h6>
    <hr>
    <div class="col-12 col-lg-4">
      <%= render  partial: 'form', locals: { model_class: model_class, group: @group }  %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<% if notice %>
  <div class="alert border-0 border-start border-5 border-success alert-dismissible fade show py-2">
    <div class="d-flex align-items-center">
      <div class="font-35 text-success"><i class="bx bxs-check-circle"></i>
      </div>
      <div class="ms-3">
        <h6 class="mb-0 text-success">Sucesso!</h6>
        <div><%= notice %></div>
      </div>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <h6 class="card-title">Listagem de Grupos</h6>
    <hr>
    <table class="table mb-3 table-hover table-responsive card-table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Status</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <th scope="row"><%= group.id %></th>
            <td><%= group.name %></td>
            <td><%= group.status_i18n %></td>
            <td>
              <%= link_to 'Exibir', group, class:"btn btn-success" %>
              <%= link_to 'Editar', edit_group_path(group), class:"btn btn-primary" %>
              <%= link_to 'Apagar', group, class:"btn btn-danger", method: :delete, data: { confirm: 'Tem certeza que quer apagar esse grupo?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to new_group_path, class:"btn btn-primary" do %>
      Novo Grupo
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="card">
  <div class="card-body">
    <h6 class="card-title">Novo Grupo</h6>
    <hr>
    <div class="col-12 col-lg-4">
      <%= render  partial: 'form', locals: { model_class: model_class, group: @group }  %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<% if notice %>
  <div class="alert border-0 border-start border-5 border-success alert-dismissible fade show py-2">
    <div class="d-flex align-items-center">
      <div class="font-35 text-success"><i class="bx bxs-check-circle"></i>
      </div>
      <div class="ms-3">
        <h6 class="mb-0 text-success">Sucesso!</h6>
        <div><%= notice %></div>
      </div>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <h6 class="card-title">Exibindo Grupo</h6>
    <hr>
    <div class="block block-rounded block-themed">
      <div class="block-content">
        <dl class="dl-horizontal">
          <dt><strong>Nome:</strong></dt>
          <dd><%= @group.name %></dd>
          <dt><strong>Status:</strong></dt>
          <dd><%= @group.status_i18n %></dd>
          
        </dl>
      </div>
    </div>

    <%= link_to 'Editar', edit_group_path(@group), class:"btn btn-primary" %>
    <%= link_to 'Voltar', groups_path, class:"btn btn-danger" %>
  </div>
</div>