config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :profiles
  resources :users, path: :usuarios, path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  resources :groups, path: 'grupos', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end
  
  resources :dealers, path: 'lojas', path_names: { new: :cadastrar, edit: :editar } do
    member do
      get :log
    end
  end

  devise_for :users, path: :account, path_names: {
    sign_in: 'entrar',
    sign_out: 'sair',
    password: 'secret',
    confirmation: 'verificar',
    unlock: 'desbloquear',
    registration: 'minha-conta',
    sign_up: 'cadastre-se',
    edit: 'editar-perfil'
  }
  root to: 'pages#dashboard'

  get 'blank', to: "pages#blank"
  get 'chat', to: "pages#chat"
  get 'dashboard', to: "pages#chat"
  get 'home', to: "pages#index"
  
  #Routes for selects
  get 'dealers_by_group/:id', to: "select_options#dealers_by_group"

end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < AdminController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:kind, :email, :name, :cpf, :rg, :assumed_name, :corporate_name, :cnpj, :status, :vehicles_count, :evaluations_count)
    end
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kind %>
    <%= form.number_field :kind %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg %>
  </div>

  <div class="field">
    <%= form.label :assumed_name %>
    <%= form.text_field :assumed_name %>
  </div>

  <div class="field">
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :vehicles_count %>
    <%= form.number_field :vehicles_count %>
  </div>

  <div class="field">
    <%= form.label :evaluations_count %>
    <%= form.number_field :evaluations_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Email</th>
      <th>Name</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Assumed name</th>
      <th>Corporate name</th>
      <th>Cnpj</th>
      <th>Status</th>
      <th>Vehicles count</th>
      <th>Evaluations count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.kind %></td>
        <td><%= client.email %></td>
        <td><%= client.name %></td>
        <td><%= client.cpf %></td>
        <td><%= client.rg %></td>
        <td><%= client.assumed_name %></td>
        <td><%= client.corporate_name %></td>
        <td><%= client.cnpj %></td>
        <td><%= client.status %></td>
        <td><%= client.vehicles_count %></td>
        <td><%= client.evaluations_count %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @client.kind %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @client.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @client.rg %>
</p>

<p>
  <strong>Assumed name:</strong>
  <%= @client.assumed_name %>
</p>

<p>
  <strong>Corporate name:</strong>
  <%= @client.corporate_name %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @client.cnpj %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<p>
  <strong>Vehicles count:</strong>
  <%= @client.vehicles_count %>
</p>

<p>
  <strong>Evaluations count:</strong>
  <%= @client.evaluations_count %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>